version: '3.9'
services:
  otel-collector:
    container_name: otel-collector
    hostname: pt-instance-1
    image: otel/opentelemetry-collector-contrib
    environment:
      - DD_SITE
      - DD_API_KEY
    volumes:
      - $PWD/section00/activity/collector-with-log.yaml:/etc/otelcol-contrib/config.yaml
      - /var/log/test/:/var/log/test/
    network_mode: host

  springotel:
    container_name: springotel
    hostname: pt-instance-1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $PWD/:/root/oteljavalab/
      - /var/log/test/:/var/log/test/
    stdin_open: true
    tty: true
    command: "sleep infinity"
    network_mode: host


